server:
  port: 8082
spring:
  application:
    name: OperationRegister
  h2:
    console:
      enabled : "true"
      path : "/h2"
  datasource:
    url: "jdbc:h2:mem:memDb"
    driverClassName : "org.h2.Driver"
    username : "atr"
    password : "123"